/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20Like,
  IERC20LikeInterface,
} from "../../../contracts/SimpleV2Router.sol/IERC20Like";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20Like__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20LikeInterface {
    return new Interface(_abi) as IERC20LikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC20Like {
    return new Contract(address, _abi, runner) as unknown as IERC20Like;
  }
}
