/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFactoryLike,
  IFactoryLikeInterface,
} from "../../../contracts/SimpleV2Router.sol/IFactoryLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "createPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFactoryLike__factory {
  static readonly abi = _abi;
  static createInterface(): IFactoryLikeInterface {
    return new Interface(_abi) as IFactoryLikeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFactoryLike {
    return new Contract(address, _abi, runner) as unknown as IFactoryLike;
  }
}
