/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as loanManagerSol from "./LoanManager.sol";
export { MockToken__factory } from "./MockToken__factory";
