/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Like } from "./IERC20Like";
export type { IFactoryLike } from "./IFactoryLike";
export type { IPairLike } from "./IPairLike";
export type { SimpleV2Router } from "./SimpleV2Router";
